"""Writes i18n/strings.csv (Godot translation CSV) from the table below. Run: python3 tools/strings.py"""
import csv

S = {
    "TITLE": ("균사", "HYPHA"),
    "TITLE_SUB": ("오르카급 · 운전수 하윤", "ORCA-CLASS · DRIVER HA YOON"),
    "TITLE_TAGLINE": ("1스테이지 — 균사에 먹힌 마을", "STAGE 1 — THE VILLAGE THE FUNGUS ATE"),
    "TITLE_BEST": ("최고 점수 %d", "BEST %d"),
    "MENU_START_NORMAL": ("출격 — 보통", "SORTIE — NORMAL"),
    "MENU_START_HARD": ("출격 — 어려움", "SORTIE — HARD"),
    "MENU_FROM_MIDBOSS": ("분교부터 (기록 제외)", "FROM THE SCHOOL (UNRANKED)"),
    "MENU_FROM_BOSS": ("댐부터 (기록 제외)", "FROM THE DAM (UNRANKED)"),
    "MENU_SETTINGS": ("설정", "SETTINGS"),
    "MENU_QUIT": ("종료", "QUIT"),
    "MENU_BACK": ("뒤로", "BACK"),
    "MENU_PAUSED": ("일시정지", "PAUSED"),
    "MENU_RESUME": ("계속", "RESUME"),
    "MENU_RESTART": ("다시 시작", "RESTART"),
    "MENU_QUIT_TITLE": ("타이틀로", "TO TITLE"),
    "MENU_CONTINUE_CHECKPOINT": ("체크포인트에서 이어하기", "CONTINUE FROM CHECKPOINT"),
    "MENU_RESTART_STAGE": ("처음부터", "RESTART STAGE"),
    "MENU_RETRY": ("한 판 더", "ONE MORE RUN"),
    "GAME_OVER": ("작전 실패", "MISSION FAILED"),
    "GAME_OVER_SCORE": ("점수 %d", "SCORE %d"),
    "SET_LANGUAGE": ("언어", "LANGUAGE"),
    "LANGUAGE_NAME": ("한국어", "ENGLISH"),
    "SET_MASTER": ("전체 음량", "MASTER VOLUME"),
    "SET_MUSIC": ("음악", "MUSIC"),
    "SET_SFX": ("효과음", "SOUND EFFECTS"),
    "SET_SENSITIVITY": ("조준 감도", "AIM SENSITIVITY"),
    "SET_SHAKE": ("화면 흔들림", "SCREEN SHAKE"),
    "SET_DITHER": ("디더링 강도", "DITHER"),
    "SET_CONTROLS": ("조작 설정", "CONTROLS"),
    "SET_REBIND_HELP": ("선택 후 새 키를 누르세요", "SELECT, THEN PRESS A NEW KEY"),
    "SET_RESET_BINDINGS": ("기본값으로", "RESET TO DEFAULTS"),
    "PRESS_KEY": ("키 입력…", "PRESS…"),
    "ACTION_MOVE_FORWARD": ("전진", "FORWARD"),
    "ACTION_MOVE_BACK": ("후진", "BACK"),
    "ACTION_MOVE_LEFT": ("왼쪽", "LEFT"),
    "ACTION_MOVE_RIGHT": ("오른쪽", "RIGHT"),
    "ACTION_FIRE_COAX": ("동축기관총", "COAXIAL GUN"),
    "ACTION_FIRE_CANNON": ("주포", "MAIN GUN"),
    "ACTION_TAIL": ("꼬리", "TAIL"),
    "ACTION_ANCHOR": ("꼬리 박기 (급정지·드리프트)", "ANCHOR (STOP / DRIFT)"),
    "ACTION_OVERDRIVE": ("오버드라이브", "OVERDRIVE"),
    "ACTION_BRAKE": ("브레이크", "BRAKE"),
    "ACTION_PAUSE": ("일시정지", "PAUSE"),
    "MOUSE_1": ("마우스 왼쪽", "LMB"),
    "MOUSE_2": ("마우스 오른쪽", "RMB"),
    "MOUSE_3": ("마우스 가운데", "MMB"),
    "MOUSE_8": ("마우스 4", "MOUSE 4"),
    "MOUSE_9": ("마우스 5", "MOUSE 5"),
    "HUD_ARMOR": ("장갑", "ARMOR"),
    "HUD_TAIL": ("꼬리", "TAIL"),
    "HUD_READY": ("준비", "READY"),
    "HUD_BRAKE": ("감속", "BRAKE"),
    "HUD_BOOST": ("가속", "BOOST"),
    "HUD_COAX": ("동축", "COAX"),
    "HUD_LASER": ("레이저", "LASER"),
    "HUD_OVERHEAT": ("과열", "OVERHEAT"),
    "HUD_ENGAGE": ("요격", "ENGAGE"),
    "HUD_COMBO": ("%d 연속", "%d CHAIN"),
    "ROUND_APHE": ("철갑유탄", "APHE"),
    "ROUND_HEAT": ("대전차고폭탄", "HEAT"),
    "ROUND_CANISTER": ("산탄", "CANISTER"),
    "ROUND_DRAGON": ("용의 숨결", "DRAGON'S BREATH"),
    "ROUND_APFSDS": ("날개안정분리철갑탄", "APFSDS"),
    "ROUND_AIRBURST": ("공중폭발탄", "AIRBURST"),
    "PICKUP_COAX": ("동축 강화", "COAX UP"),
    "PICKUP_HEAT": ("대전차고폭탄", "HEAT"),
    "PICKUP_CANISTER": ("산탄", "CANISTER"),
    "PICKUP_DRAGON": ("용의 숨결", "DRAGON'S BREATH"),
    "PICKUP_APFSDS": ("날개안정분리철갑탄", "APFSDS"),
    "PICKUP_AIRBURST": ("공중폭발탄", "AIRBURST"),
    "PICKUP_REPAIR": ("수리", "REPAIR"),
    "PICKUP_LIFE": ("예비 차체", "SPARE HULL"),
    "SECTION_0": ("농로", "FARM ROAD"),
    "SECTION_1": ("마을", "VILLAGE"),
    "SECTION_2": ("분교", "BRANCH SCHOOL"),
    "SECTION_3": ("저수지", "RESERVOIR"),
    "SECTION_4": ("고가도로", "OVERPASS"),
    "SECTION_5": ("댐", "THE DAM"),
    "CHECKPOINT": ("체크포인트", "CHECKPOINT"),
    "SPEAKER_HY": ("하윤", "HA YOON"),
    "SPEAKER_CT": ("관제", "CONTROL"),
    "BOSS_COLOSSUS": ("균사 거인", "HYPHAL COLOSSUS"),
    "BOSS_HELICOPTER": ("감염된 공격헬기", "INFECTED GUNSHIP"),
    "HINT_CONTROLS": ("WASD 이동 · 좌클릭 동축 · 우클릭 주포 · 스페이스 꼬리 · Q 꼬리 박기 · Shift/Ctrl 가속/감속",
                      "WASD MOVE · LMB COAX · RMB MAIN GUN · SPACE TAIL · Q ANCHOR · SHIFT/CTRL BOOST/BRAKE"),
    "HINT_TAIL": ("스페이스: 꼬리로 아이템 낚아채기 · 적 붙잡아 던지기", "SPACE: SNATCH ITEMS · GRAB AND THROW ENEMIES"),
    "HINT_ANCHOR": ("Q + 방향: 꼬리로 드리프트 회피", "Q + DIRECTION: TAIL DRIFT DODGE"),
    "STAGE_CLEAR": ("1스테이지 돌파", "STAGE 1 CLEAR"),
    "RESULT_SCORE": ("점수", "SCORE"),
    "RESULT_KILLS": ("격파율", "KILLS"),
    "RESULT_ACCURACY": ("주포 명중률", "MAIN GUN ACCURACY"),
    "RESULT_MAX_COMBO": ("최대 연속", "MAX CHAIN"),
    "RESULT_DAMAGE": ("받은 피해", "DAMAGE TAKEN"),
    "RESULT_TIME": ("시간", "TIME"),
    "RESULT_RANK": ("등급", "RANK"),
    "RESULT_NEW_BEST": ("최고 기록!", "NEW BEST!"),
    "RESULT_UNRANKED": ("체크포인트 시작 — 기록 제외", "STARTED FROM CHECKPOINT — UNRANKED"),
    # Radio. HY_ is Ha Yoon, CT_ is Control.
    "HY_INTRO": ("오르카, 균사 구역 진입. …논이 전부 분홍색이네.", "Orca entering the hypha zone. ...The paddies have all gone pink."),
    "CT_BRIEF": ("관제. 마을을 지나 저수지 댐까지 돌파한다. 무인기 신호 다수.", "Control. Push through the village to the reservoir dam. Multiple drone signals."),
    "HY_DRONES": ("FPV다. 빨간 불 켜지면 들이받는다.", "FPVs. When the light goes red, they dive."),
    "HY_BEHIND": ("뒤에서 온다!", "Six o'clock!"),
    "CT_UGV": ("무인 전차 확인. 대전차 미사일 조심.", "UGVs confirmed. Watch for ATGMs."),
    "HY_VILLAGE": ("할머니 댁 같은 동네네. …죄송해요, 좀 부술게요.", "Looks like grandma's village. ...Sorry. I'm going to break some things."),
    "CT_UAV": ("고정익 무인기, 폭격 접근!", "Fixed-wing UAVs on a bombing run!"),
    "HY_FUNGUS": ("비닐하우스에서 뭔가 기어 나온다.", "Something's crawling out of the greenhouses."),
    "CT_SPITTER": ("포자 박격 개체. 착탄 표시를 피해.", "Spore mortars. Stay out of the marked circles."),
    "HY_SCHOOL": ("분교다. 운동장이… 숨을 쉬고 있어.", "The branch school. The schoolyard is... breathing."),
    "CT_MIDBOSS": ("대형 균사체. 빛나는 결절을 태워.", "Massive fungal body. Burn the glowing nodes."),
    "HY_CORE": ("핵이 드러났다. 지금이야!", "The core's open. Now!"),
    "HY_JUMP": ("전면 휩쓸기! Q로 꼬리 박고 빠져!", "Full sweep! Anchor with Q and slip it!"),
    "HY_MIDBOSS_DOWN": ("쓰러졌다. 계속 간다.", "It's down. Moving on."),
    "HY_RESERVOIR": ("저수지. 갈대 속에 뭔가 있어.", "The reservoir. Something's in the reeds."),
    "CT_SPORE_STORM": ("포자 폭풍. 시야 확보 어려움.", "Spore storm. Visibility dropping."),
    "HY_OVERPASS": ("고속도로로 올라간다.", "Taking the highway."),
    "HY_QUIET": ("…조용하네.", "...Quiet."),
    "CT_ROTOR": ("로터음 접근! 공격헬기다!", "Rotor noise closing! Attack helicopter!"),
    "HY_BOSS": ("저것도 먹혔어. 조종사는… 아니, 생각하지 말자.", "That one's infected too. The pilot... no. Don't think about it."),
    "CT_BOSS_PHASE2": ("장갑판 탈락! 놈이 붙는다!", "Armor panels off! It's closing in!"),
    "HY_BOSS_PHASE3": ("균사가 기체를 삼켰어…!", "The fungus swallowed the airframe...!"),
    "HY_CLEAR": ("…끝났다. 오르카, 복귀한다.", "...It's over. Orca, returning."),
    "HY_LOW_ARMOR": ("장갑 한계야!", "Armor's failing!"),
    "CT_LIFE_LOST": ("오르카, 응답하라! …예비 차체 투입.", "Orca, respond! ...Deploying spare hull."),
    "HY_CIWS_OVERHEAT": ("레이저 과열! 직접 피해야 해.", "Laser's overheating! I have to dodge!"),
    "CT_NO_DAMAGE": ("무피해 돌파. 좋아.", "Clean run. Nice."),
}

with open("i18n/strings.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["keys", "ko", "en"])
    for key, (ko, en) in S.items():
        w.writerow([key, ko, en])
print(len(S), "strings")
