"""Writes i18n/strings.csv (Godot translation CSV) from the table below. Run: python3 tools/strings.py"""
import csv

S = {
    "TITLE": ("orca class", "orca class"),
    "TITLE_SUB": ("범고래급 · 운전수 하윤", "ORCA-CLASS · DRIVER HA YOON"),
    "TITLE_TAGLINE": ("1스테이지 — 균사에 먹힌 마을", "STAGE 1 — THE VILLAGE THE FUNGUS ATE"),
    "TITLE_BEST": ("최고 점수 %d", "BEST %d"),
    "MENU_TUTORIAL": ("처음이라면 — 조작 연습", "FIRST TIME? LEARN THE CONTROLS"),
    "TUTORIAL_TITLE": ("조작 연습", "Learn the controls"),
    "TUTORIAL_STEP": ("조작 연습  %d / %d", "Practice  %d / %d"),
    "TUTORIAL_WELCOME": (
        "아래 보이는 전차를 직접 움직여 볼 거예요. 여기서는 공격받지 않아요.\n천천히 읽으세요. 준비되면 아래 '연습 시작'을 누르세요.",
        "You'll drive the tank below. Nothing here will attack you.\nTake your time. Click 'Begin practice' below when you're ready.",
    ),
    "TUTORIAL_LEFT": (
        "%s\n전차가 화면 왼쪽으로 움직여요. 움직인 뒤에는 손을 떼세요.",
        "%s\nThe tank moves to the left of the screen. Then let go.",
    ),
    "TUTORIAL_RIGHT": (
        "%s\n전차가 화면 오른쪽으로 움직여요. 움직인 뒤에는 손을 떼세요.",
        "%s\nThe tank moves to the right of the screen. Then let go.",
    ),
    "TUTORIAL_FORWARD": (
        "%s\n화면 위쪽으로 조금 가 보세요. 다 움직였으면 손을 떼세요.",
        "%s\nDrive a little toward the top of the screen, then let go.",
    ),
    "TUTORIAL_BACK": (
        "%s\n화면 아래쪽으로 조금 내려온 뒤 손을 떼세요.",
        "%s\nDrive a little toward the bottom of the screen, then let go.",
    ),
    "TUTORIAL_STOP": (
        "누르고 있던 이동 키에서 손을 떼세요. 전차가 멈춰요.\n이 연습장에서는 손을 떼면 멈추지만, 본 게임에서는 길을 따라 계속 전진해요.",
        "Let go of the movement keys. The tank stops.\nIn the main game, it keeps driving along the road even when you let go.",
    ),
    "TUTORIAL_AIM": (
        "마우스를 책상 위에서 천천히 움직여 보세요. 화면의 + 표시가 따라와요.\n+ 표시를 노란 동그라미 안으로 옮기세요. 아직 버튼은 누르지 마세요.",
        "Move your mouse slowly across your desk. The + on screen follows it.\nMove the + inside the yellow circle. Don't press a button yet.",
    ),
    "TUTORIAL_FIRE": (
        "+ 표시를 노란 동그라미 안에 놓으세요. %s\n누르고 있으면 주포가 발사돼요. 빗나가도 괜찮아요. 다시 겨누고 눌러 보세요.",
        "Keep the + inside the yellow circle. %s\nThe main gun fires after a short hold. If you miss, aim and try again.",
    ),
    "TUTORIAL_DONE": (
        "이동하고 표적을 맞혔어요. 여기서 더 연습해도 돼요.\n본 게임에서는 겨눈 적에게 기관총도 자동으로 쏴요. '쉬움으로 시작'을 누르면 본 게임으로 가요.",
        "You've moved the tank and hit the target. You can keep practicing here.\nIn the main game, machine guns also fire at enemies you aim at. 'Play on easy' starts the game.",
    ),
    "TUTORIAL_BEGIN": ("연습 시작", "Begin practice"),
    "TUTORIAL_NEXT": ("다음", "Next"),
    "TUTORIAL_START_GAME": ("쉬움으로 시작", "Play on easy"),
    "TUTORIAL_LEAVE": ("첫 화면으로", "Back to title"),
    "TUTORIAL_RESTART": ("처음부터 연습", "Practice again"),
    "TUTORIAL_OK": ("됐어요. 준비되면 아래 '다음'을 누르세요.", "Done. Click 'Next' below when you're ready."),
    "TUTORIAL_HIT": ("표적에 맞았어요. 아래 '다음'을 누르세요.", "You hit the target. Click 'Next' below."),
    "TUTORIAL_KEY": ("키보드에서 %s 키를 찾아 누르고 있어 보세요.", "Find the %s key on your keyboard and hold it down."),
    "TUTORIAL_STICK": ("왼쪽 스틱을 '%s' 방향으로 기울이세요.", "Push the left stick in the %s direction."),
    "TUTORIAL_TRIGGER": ("오른쪽 방아쇠 버튼을 계속 누르세요.", "Hold down the right trigger."),
    "TUTORIAL_MOUSE_1": ("마우스 왼쪽 버튼을 계속 누르세요.", "Hold down the left mouse button."),
    "TUTORIAL_MOUSE_2": ("마우스 오른쪽 버튼을 계속 누르세요.", "Hold down the right mouse button."),
    "TUTORIAL_MOUSE_3": ("마우스 가운데 버튼을 계속 누르세요.", "Hold down the middle mouse button."),
    "TUTORIAL_MOUSE_8": ("마우스 4번 버튼을 계속 누르세요.", "Hold down mouse button 4."),
    "TUTORIAL_MOUSE_9": ("마우스 5번 버튼을 계속 누르세요.", "Hold down mouse button 5."),
    "TUTORIAL_STOP_PAD": (
        "왼쪽 스틱에서 손을 떼세요. 전차가 멈춰요.\n이 연습장에서는 손을 떼면 멈추지만, 본 게임에서는 길을 따라 계속 전진해요.",
        "Let go of the left stick. The tank stops.\nIn the main game, it keeps driving along the road even when you let go.",
    ),
    "TUTORIAL_AIM_PAD": (
        "오른쪽 스틱을 천천히 기울여 보세요. 화면의 + 표시가 따라와요.\n+ 표시를 노란 동그라미 안으로 옮기세요. 아직 버튼은 누르지 마세요.",
        "Tilt the right stick slowly. The + on screen follows it.\nMove the + inside the yellow circle. Don't press a button yet.",
    ),
    "MENU_START_EASY": ("출격 — 쉬움", "SORTIE — EASY"),
    "MENU_START_NORMAL": ("출격 — 보통", "SORTIE — NORMAL"),
    "MENU_START_HARD": ("출격 — 어려움", "SORTIE — HARD"),
    "MENU_FROM_MIDBOSS": ("분교부터 (기록 제외)", "FROM THE SCHOOL (UNRANKED)"),
    "MENU_FROM_BOSS": ("댐부터 (기록 제외)", "FROM THE DAM (UNRANKED)"),
    "MENU_DEBUG_ROOM": ("디버그 룸", "DEBUG ROOM"),
    "MENU_SETTINGS": ("설정", "SETTINGS"),
    "MENU_QUIT": ("종료", "QUIT"),
    "MENU_BACK": ("뒤로", "BACK"),
    "MENU_PAUSED": ("일시정지", "PAUSED"),
    "MENU_RESUME": ("계속", "RESUME"),
    "MENU_RESTART": ("다시 시작", "RESTART"),
    "MENU_QUIT_TITLE": ("타이틀로", "TO TITLE"),
    "MENU_CONTINUE_CHECKPOINT": ("체크포인트에서 이어하기", "CONTINUE FROM CHECKPOINT"),
    "MENU_RESTART_STAGE": ("처음부터", "RESTART STAGE"),
    "MENU_RETRY": ("한 판 더", "ONE MORE RUN"),
    "GAME_OVER": ("작전 실패", "MISSION FAILED"),
    "GAME_OVER_SCORE": ("점수 %d", "SCORE %d"),
    "SET_LANGUAGE": ("언어", "LANGUAGE"),
    "LANGUAGE_NAME": ("한국어", "ENGLISH"),
    "SET_MASTER": ("전체 음량", "MASTER VOLUME"),
    "SET_MUSIC": ("음악", "MUSIC"),
    "SET_SFX": ("효과음", "SOUND EFFECTS"),
    "SET_SENSITIVITY": ("조준 감도", "AIM SENSITIVITY"),
    "SET_SHAKE": ("화면 흔들림", "SCREEN SHAKE"),
    "SET_DITHER": ("디더링 강도", "DITHER"),
    "SET_CONTROLS": ("조작 설정", "CONTROLS"),
    "SET_REBIND_HELP": ("선택 후 새 키를 누르세요", "SELECT, THEN PRESS A NEW KEY"),
    "SET_RESET_BINDINGS": ("기본값으로", "RESET TO DEFAULTS"),
    "PRESS_KEY": ("키 입력…", "PRESS…"),
    "ACTION_MOVE_FORWARD": ("전진", "FORWARD"),
    "ACTION_MOVE_BACK": ("후진", "BACK"),
    "ACTION_MOVE_LEFT": ("왼쪽", "LEFT"),
    "ACTION_MOVE_RIGHT": ("오른쪽", "RIGHT"),
    "ACTION_FIRE": ("발사", "FIRE"),
    "ACTION_DASH": ("대시", "DASH"),
    "ACTION_COAX": ("기총", "COAX"),
    "ACTION_PAUSE": ("일시정지", "PAUSE"),
    "MOUSE_1": ("마우스 왼쪽", "LMB"),
    "MOUSE_2": ("마우스 오른쪽", "RMB"),
    "MOUSE_3": ("마우스 가운데", "MMB"),
    "MOUSE_8": ("마우스 4", "MOUSE 4"),
    "MOUSE_9": ("마우스 5", "MOUSE 5"),
    "ROUND_APHE": ("철갑유탄", "APHE"),
    "ROUND_HEAT": ("대전차고폭탄", "HEAT"),
    "ROUND_CANISTER": ("산탄", "CANISTER"),
    "ROUND_DRAGON": ("용의 숨결", "DRAGON'S BREATH"),
    "ROUND_APFSDS": ("날개안정분리철갑탄", "APFSDS"),
    "ROUND_AIRBURST": ("공중폭발탄", "AIRBURST"),
    "ROUND_ATGM": ("대전차미사일", "ATGM"),
    "ROUND_MICRO": ("마이크로미사일", "MICRO-MISSILE"),
    "PICKUP_COAX": ("동축 강화", "COAX UP"),
    "PICKUP_HEAT": ("대전차고폭탄", "HEAT"),
    "PICKUP_CANISTER": ("산탄", "CANISTER"),
    "PICKUP_DRAGON": ("용의 숨결", "DRAGON'S BREATH"),
    "PICKUP_APFSDS": ("날개안정분리철갑탄", "APFSDS"),
    "PICKUP_AIRBURST": ("공중폭발탄", "AIRBURST"),
    "PICKUP_ATGM": ("대전차미사일", "ATGM"),
    "PICKUP_MICRO": ("마이크로미사일", "MICRO-MISSILE"),
    "PICKUP_REPAIR": ("수리", "REPAIR"),
    "PICKUP_ERA": ("반응장갑", "REACTIVE ARMOR"),
    "PICKUP_TAIL": ("꼬리 재생", "TAIL REGROWTH"),
    "PICKUP_RWS": ("레이저 RWS 장착", "RWS MOUNTED"),
    "PICKUP_LIFE": ("예비 차체", "SPARE HULL"),
    "STYLE_CRUSH": ("깔아뭉개기", "CRUSHED"),
    "STYLE_LASH": ("후려치기", "LASH"),
    "STYLE_THROWN": ("투척", "THROWN"),
    "STYLE_BURNED": ("소각", "BURNED"),
    "STYLE_AIRBURST": ("공중폭발", "AIRBURST"),
    "STYLE_ZAPPED": ("레이저", "ZAPPED"),
    "STYLE_COAX": ("사살", "GUNNED"),
    "STYLE_COLLATERAL": ("연쇄 폭발", "COLLATERAL"),
    "STYLE_SPLASH": ("폭풍", "SPLASH"),
    "STYLE_SKYSHOT": ("대공 직격", "SKYSHOT"),
    "STYLE_DIRECT": ("직격", "DIRECT HIT"),
    "STYLE_CHARGED": ("충전 직격", "CHARGED"),
    "STYLE_INTERRUPT": ("시전 저지", "INTERRUPT"),
    "STYLE_MULTIKILL": ("다중 처치", "MULTIKILL"),
    "STYLE_MASSACRE": ("학살", "MASSACRE"),
    "STYLE_ANNIHILATION": ("섬멸", "ANNIHILATION"),
    "STYLE_DEMOLITION": ("철거", "DEMOLITION"),
    "STYLE_DEFLECT": ("쳐내기", "DEFLECT"),
    "STYLE_REFLECT": ("반사", "REFLECT"),
    "STYLE_CLOSE_CALL": ("구사일생", "CLOSE CALL"),
    "STYLE_SNATCH": ("낚아채기", "SNATCHED"),
    "STYLE_GIANT": ("거물 사냥", "GIANT SLAYER"),
    "SECTION_0": ("농로", "FARM ROAD"),
    "SECTION_1": ("마을", "VILLAGE"),
    "SECTION_2": ("분교", "BRANCH SCHOOL"),
    "SECTION_3": ("저수지", "RESERVOIR"),
    "SECTION_4": ("고가도로", "OVERPASS"),
    "SECTION_5": ("댐", "THE DAM"),
    "CHECKPOINT": ("체크포인트", "CHECKPOINT"),
    "CALLOUT_INTERCEPT": ("요격!", "INTERCEPT!"),
    "CALLOUT_INCOMING": ("접근!", "INCOMING!"),
    "HUD_FPS": ("FPS %d", "FPS %d"),
    "SPEAKER_AI": ("범고래급 전투 보조", "ORCA COMBAT ASSIST"),
    "BOSS_COLOSSUS": ("균사 거인", "HYPHAL COLOSSUS"),
    "BOSS_GUNSHIP": ("감염된 대형 건십", "INFECTED HEAVY GUNSHIP"),
    "SHOUT_MISSION_START": ("작전 개시!!", "MISSION START!!"),
    "WARN_FCS_LOST": ("FCS 파괴! 락온 불가", "FCS LOST! NO LOCK"),
    "WARN_RWS_LOST": ("RWS 파괴! 요격 불가", "RWS LOST! NO INTERCEPTS"),
    "SHOUT_MISSION_COMPLETE": ("작전 완료!!", "MISSION COMPLETE!!"),
    "STAGE_CLEAR": ("1스테이지 돌파", "STAGE 1 CLEAR"),
    "RESULT_SCORE": ("점수", "SCORE"),
    "RESULT_KILLS": ("격파율", "KILLS"),
    "RESULT_ACCURACY": ("주포 명중률", "MAIN GUN ACCURACY"),
    "RESULT_MAX_COMBO": ("최대 연속", "MAX CHAIN"),
    "RESULT_DAMAGE": ("받은 피해", "DAMAGE TAKEN"),
    "RESULT_TIME": ("시간", "TIME"),
    "RESULT_RANK": ("등급", "RANK"),
    "RESULT_NEW_BEST": ("최고 기록!", "NEW BEST!"),
    "RESULT_UNRANKED": ("체크포인트 시작 — 기록 제외", "STARTED FROM CHECKPOINT — UNRANKED"),
}

with open("i18n/strings.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f, lineterminator="\n")
    w.writerow(["keys", "ko", "en"])
    for key, (ko, en) in S.items():
        w.writerow([key, ko, en])
print(len(S), "strings")
